
import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations{
  @override
  Map<String,Map<String,String>> get keys =>{

    'en_US' :{
      "registerView_btm":"By continuing you automatically agree to AI Muspal's Terms of Use and Privacy Policy.",
      'EmailContinueButton_txt':"Continue by Email",
      'EmailView_1st':"Enter your email address",
      'EmailView_2nd' :'We will send a 6-digit verification code',
      'EmailView_btn':'Next step',
      'EmailInputField_labelText':"Email address",
      'EmailInputField_hintText':"johndoe@gmail.com",
      "OtpView_1st":'Enter the 6-digit verification code',
      "OtpView_2nd":'We have sent a verification code to Johnxxx@gmail.com',
      "OtpForm_1st":'Resend verification code',
      "OtpForm_2nd":'You can resend after seconds',
      "WelcomeView_1st":"Let's start chatting",
      "WelcomeView_2nd":"You have successfully registered",
      "WelcomeView_btn":"Go to experience",
      "HomeView_1st":"Your",
      "HomeView_2nd":"Music Master",
      "HomeView_3rd":"Learn all about music theory",
      "HomeView_4th":"Start a conversation",
      "HomeView_5th":"AI function",
      "ProfileView_title":"Account",
      "ProfileView_Subscribe":"Subscribe",
      "ProfileView_1st":"general member",
      "ProfileView_2nd":"You are currently using the free membership plan, upgrade to get more tokens and send more messages per day",
      "ProfileView_3rd":"Program includes",
      "ProfileView_4th":"5 messages per day",
      "ProfileView_5th":"Maximum length of each message \n is 500 characters",
      "ProfileView_6th":"Up to 15 minutes of AI audio rating per month",
      "ProfileView_7th":"5 music analysis reports per month",
      "ProfileView_8th":"Upgrade Membership",
      "ProfileView_9th":"About Us",
      "ProfileView_10th":"Contact Us",
      "ProfileView_11th":"Terms of Service",
      "ProfileView_12th":"Privacy",
      "ProfileView_13th":"Sign out",
      "ProfileView_14th":"Delete Account",
      "ProfileView_15th":"Are you sure you want to log out?",
      "ProfileView_16th":"Sign out",
      "ProfileView_17th":"Cancel",
      "ProfileView_18th":"Are you sure you want to permanently delete your account?",
      "ProfileView_19th":"All data associated with your account will be deleted and cannot be recovered.",
      "ProfileView_20th":"Account delete",
      "ProfileView_21th":"Account delete successfully",
      "ProfileView_22th":"Delete account",
      "ProfileView_23th":"Delete account",
      "ProfileView_24th":"Cancel",
      "ContactView_1st":"Contact Us",
      "ContactView_2nd":"If you have any questions or need assistance, please feel free to contact us via email. We will get back to you as soon as possible.",
      "ContactView_3rd":"Email address",
      "TermsOfServiceView_1st":"Terms of Service",
      "TermsOfServiceView_2nd":"Fake pavilion young talent Zhuzi went to the lamp only to announce the installation of the south, happy bath rice open red elephant tiger before the inch blessing. Buy a nose too bright 'enter the winter sound with the past plant full heavy words home' Ding brother hundred send flat dry today color collection, Guan Mao plant today drink two red ten stand because of class full beg buy help 'brother copy master evening eyes' Bena.",
      "TermsOfServiceView_3rd":"Mouth past teaching or ten you will light early ocean love left present dad import blowing Xiao anti too! Past nose empty south owe far Pakistan gas eye day. Father from the flower often. It sound down eat right how year that is sound because butterfly not who, a sign outside day called buy clothes see? Outside put with phase hair forest.",
      "TermsOfServiceView_4th":"The cup is good. Quickly buy her A with high waves. The evening wind only loves the old sister. The side blows, and the old man blows in. The world is due to the time. The more ancestors, the more they understand. The book is from the north. The lotus is far away from the courtyard. After dinner, the door is very afraid of the gas. The words are used in autumn and summer. Zi Jin Hu Youyou Shao sent Cai Qi and you are beautiful in the new language.",
      "TermsOfServiceView_5th":"Don't two dishes 'Spring Green Fire Open' from the bottom stop back to the ancient more open hat to ask the evening blessing has yellow. Inside the seven strong songs beside the ten, the pavilion road five butterflies thousands of river shells, pine stretch open. The cattle strong autumn cat it rains in the sky tell many butterflies food loaded stone.",
      "TermsOfServiceView_6th":"Pick back to send two gods to dig bitter how to say things. Also green through the flesh of the flower sound Yang Zhuang; to the six questions climb the sound of the inch people plant young complain evening line two mountains? Household borrowed to Guanyang evening lotus Chang brother, father green people step together room also Zhu Shi Hui can endure garden bitter! Left outside the tail? Do shells from the sky, the pavilion spring I. Household ruler painting.",
      "TermsOfServiceView_7th":"vening country urgent level Yingyang hand egg rises Dan eats and flies wind will Zhu! You send temple is jumping drink since now feather urgent tail full too strip owe, that is to show strange that horse temple, food country several color room learn fine year door summer root.",
      "TermsOfServiceView_8th":"The last of my children you now have all the things in the class right to complain. She took the North language girl meat pen shoot through the butterfly bright beg blade help, caught the class rain home land Ni, Ji from the B school, Zhu Ge land tree hide two ancestors.",
      "TermsOfServiceView_9th":"Beiyuan is also like. One yuan to support milk, the ear wind wrong words will be yang milk borrowed to buy the past and the summer air thought.",
      "PrivacyView_title":"Privacy",
      "UpgarteMemberShiftView_title":"Upgrade AI MusPal",
      "UpgarteMemberShiftView_1st":"Valuable Member",
      "UpgarteMemberShiftView_2nd":"Platinum Member",
      "ValuedMemberView_c1_1st":"Annual Fee Plan",
      "ValuedMemberView_c1_2nd":"HK\$238.5/month",
      "ValuedMemberView_c1_3rd":"HK\$2,862/year",
      "ValuedMemberView_c2_1st":"100 messages per month",
      "ValuedMemberView_c2_2nd":"Maximum length per message: 1,000 characters",
      "ValuedMemberView_c2_3rd":"Up to 4 hours of AI audio rating per month",
      "ValuedMemberView_c2_4th":"300 music analysis reports per month",
      "ValuedMemberView_c3_title":"Auto-renewal instructions",
      "ValuedMemberView_c3_1st":"1. Payment: 'Monthly/quarterly/annual subscriptions' are automatically renewed products. After confirming the purchase, the payment will be deducted from your Apple iTunes account;",
      "ValuedMemberView_c3_2nd":"2. Renewal: 24 hours before your subscription expires, Apple will automatically deduct the fee from your iTunes account. If the renewal is successful, the membership period will be automatically extended.",
      "ValuedMemberView_c3_3rd":"3. If you need to cancel automatic renewal, please manually turn off automatic renewal in the Apple ID account settings at least 24 hours before the subscription expires. No more charges will be made after turning it off.",
      "ValuedMemberView_textField_btn":"Apply",
      "ValuedMemberView_textField_hint":"Enter referral code",
      "ValuedMemberView_roundbtn":"Start your 3-day free trial",
      "ValuedMemberView_bottom":"After subscribing, you will be automatically charged HK\$6528/year. You can manage your subscription by cancelling it in the App store. Terms of Use.",
    },

    'zh_CN' :{
      "registerView_btm":"繼續操作即表示您自動同意 AI Muspal 的使用條款和隱私權政策。",
      'EmailContinueButton_txt':"使用Email繼續",
      'EmailView_1st':"輸入你的電郵地址",
      "EmailView_2nd":'我們會發送6位數驗證碼',
      "EmailView_btn":'下一步',
      "EmailInputField_labelText":'電郵地址',
      "EmailInputField_hintText":'johndoe@gmail.com',
      "OtpView_1st":'輸入6位數驗證碼',
      "OtpView_2nd":'我們已發送驗證碼到Johnxxx@gmail.com',
      "OtpForm_1st":'重新發送驗證碼',
      "OtpForm_2nd":'秒後可重新發送',
      "WelcomeView_1st":'開始聊天吧',
      "WelcomeView_2nd":'你已成功註冊',
      "WelcomeView_btn":'前往體驗',
      "HomeView_1st":'您的',
      "HomeView_2nd":'音樂大師',
      "HomeView_3rd":'學習一切樂理知識',
      "HomeView_4th":'開始對話',
      "HomeView_5th":'AI功能',
      "ProfileView_title":"帳戶",
      "ProfileView_Subscribe":"訂閱",
      "ProfileView_1st":"一般會員",
      "ProfileView_2nd":"你現在正在使用免費會員計劃，升級以獲得更多代幣, 每日可以發送更多訊息",
      "ProfileView_3rd":"計劃包括",
      "ProfileView_4th":"每日 5 條訊息",
      "ProfileView_5th":"每條訊息最多 500 字",
      "ProfileView_6th":"每月最多15分鐘的AI音頻評分",
      "ProfileView_7th":"每月5份音樂分析報告",
      "ProfileView_8th":"升級會員",
      "ProfileView_9th":"關於我們",
      "ProfileView_10th":"聯絡我們",
      "ProfileView_11th":"服務條款",
      "ProfileView_12th":"隱私",
      "ProfileView_13th":"登出",
      "ProfileView_14th":"刪除帳戶",
      "ProfileView_15th":"你確定你要登出嗎",
      "ProfileView_16th":"登出",
      "ProfileView_17th":"取消",
      "ProfileView_18th":"您確定要永久刪除您的帳戶嗎？",
      "ProfileView_19th":"與您帳戶關聯的所有資料都將被刪除且無法恢復。",
      "ProfileView_20th":"帐户删除",
      "ProfileView_21th":"帐号删除成功",
      "ProfileView_22th":"刪除帳戶",
      "ProfileView_23th":"刪除帳戶",
      "ProfileView_24th":"取消",
      "ContactView_1st":"聯絡我們",
      "ContactView_2nd":"如有任何問題或需要協助,歡迎隨時透過電郵與我們聯繫。我們將盡快回覆您。",
      "ContactView_3rd":"電郵地址",
      "TermsOfServiceView_1st":"服務條款",
      "TermsOfServiceView_2nd":"假亭幼才朱字往燈只告裝南，喜澡米開兌象虎前寸福。買個鼻過亮「進冬音跟昔種飽重言家」丁哥百送平化干今色彩收、貫冒植今喝事兩化紅十立過因課飽乞買幫「弟抄主晚目貝那」。",
      "TermsOfServiceView_3rd":"口昔教或十你會光早洋愛左現爸進口吹肖反太！昔鼻空南欠遠巴氣眼日。父自朵常。它聲下吃對怎年即音因蝴不誰，一兆外日叫買衣見？外把以相毛林。",
      "TermsOfServiceView_4th":"杯好告快高波買她甲。夕風話只愛姐綠老。呢助邊吹，進扒吹老。世因候。更祖哪明條北書荷太院遠飯後喝幫怕尼氣門很，話用白瓜根秋夏。子金胡由游少送彩七且你平語新語美呢。",
      "TermsOfServiceView_5th":"勿兩菜「春青火開」從下停回古更開帽問夕乍福己黃。裏七壯歌旁十，亭路五蝴千河貝，松申開。牛壯秋貓它天上雨訴多蝴食裝石。",
      "TermsOfServiceView_6th":"采回送兩神扒苦怎雲事。還青穿肉交花聲陽壯；往六問爬合聲寸人植幼訴夕行兩山？戶借往貫陽晚荷昌兄，爸青人步共室也朱什回忍能園苦！左外丟尾？做貝自，天次亭泉我。戶尺畫。",
      "TermsOfServiceView_7th":"晚國急平英央手蛋升旦吃又飛風會朱！尤送寺正跳喝自今羽急尾飽太條欠，即示怪即馬寺，食國几彩房學細年門夏根。",
      "TermsOfServiceView_8th":"尾我童几您現具西的都斤扒課右訴欠。她帶而北語女肉筆拍貫蝶亮乞刃助，抓課雨家了地尼，吉由乙校，朱歌地樹躲兩祖。",
      "TermsOfServiceView_9th":"貝原也像。一元支奶門耳風錯語會陽奶借色買昔且夏氣想到。",
      "PrivacyView_title":"隱私",
      "UpgarteMemberShiftView_title":"升級AI MusPal",
      "UpgarteMemberShiftView_1st":"尊貴會員",
      "UpgarteMemberShiftView_2nd":"白金會員",
      "ValuedMemberView_c1_1st":"年費計劃",
      "ValuedMemberView_c1_2nd":"HK\$238.5/月",
      "ValuedMemberView_c1_3rd":"HK\$2,862/年",
      "ValuedMemberView_c2_1st":"每月100條訊息",
      "ValuedMemberView_c2_2nd":"每條訊息最多 1,000 字",
      "ValuedMemberView_c2_3rd":"每月最多4小時的AI音頻評分",
      "ValuedMemberView_c2_4th":"每月300份音樂分析報告",
      "ValuedMemberView_c3_title":"自動續費說明",
      "ValuedMemberView_c3_1st":"1. 付款：“連續包月/季/年”商品為自動續費商品，確認購買後，會從您的蘋果iTunes帳戶扣費；",
      "ValuedMemberView_c3_2nd":"2. 續費：在您訂閱到期前24小時，蘋果會自動從iTunes帳戶扣費，成功後會員有效期自動延長；",
      "ValuedMemberView_c3_3rd":"3. 如需取消自動續費，請在訂閱到期前至少24小時，手動在Apple ID帳戶設置中關閉自動續費，關閉後不再扣費。",
      "ValuedMemberView_textField_btn":"套用",
      "ValuedMemberView_textField_hint":"輸入推薦碼",
      "ValuedMemberView_roundbtn":"開始 3 天免費試用",
      "ValuedMemberView_bottom":"訂閱後，你將被自動扣除HK\$ 6528/年，你可以透過App store取消式管理訂閱。使用條款 。",

    },

  };
}