
import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations{
  @override
  Map<String,Map<String,String>> get keys =>{

    'en_US' :{
      "registerView_btm":"By continuing you automatically agree to AI Muspal's Terms of Use and Privacy Policy.",
      'EmailContinueButton_txt':"Continue by Email",
      'EmailView_1st':"Enter your email address",
      'EmailView_2nd' :'We will send a 6-digit verification code',
      'EmailView_btn':'Next step',
      'EmailInputField_labelText':"Email address",
      'EmailInputField_hintText':"johndoe@gmail.com",
      "OtpView_1st":'Enter the 6-digit verification code',
      "OtpView_2nd":'We have sent a verification code to Johnxxx@gmail.com',
      "OtpForm_1st":'Resend verification code',
      "OtpForm_2nd":'You can resend after seconds',
      "WelcomeView_1st":"Let's start chatting",
      "WelcomeView_2nd":"You have successfully registered",
      "WelcomeView_btn":"Go to experience",
      "HomeView_1st":"Your",
      "HomeView_2nd":"Music Master",
      "HomeView_3rd":"Learn all about music theory",
      "HomeView_4th":"Start a conversation",
      "HomeView_5th":"AI function",
      "ProfileView_title":"Account",
      "ProfileView_Subscribe":"Subscribe",
      "ProfileView_1st":"general member",
      "ProfileView_2nd":"You are currently using the free membership plan, upgrade to get more tokens and send more messages per day",
      "ProfileView_3rd":"Program includes",
      "ProfileView_4th":"5 messages per day",
      "ProfileView_5th":"Maximum length of each message \n is 500 characters",
      "ProfileView_6th":"Up to 15 minutes of AI audio \n rating per month",
      "ProfileView_7th":"5 music analysis reports per month",
      "ProfileView_8th":"Upgrade Membership",
      "ProfileView_9th":"About Us",
      "ProfileView_10th":"Contact Us",
      "ProfileView_11th":"Terms of Service",
      "ProfileView_12th":"Privacy",
      "ProfileView_13th":"Sign out",
      "ProfileView_14th":"Delete Account",
      "ProfileView_15th":"Are you sure you want to log out?",
      "ProfileView_16th":"Sign out",
      "ProfileView_17th":"Cancel",
      "ProfileView_18th":"Are you sure you want to permanently delete your account?",
      "ProfileView_19th":"All data associated with your account will be deleted and cannot be recovered.",
      "ProfileView_20th":"Account delete",
      "ProfileView_21th":"Account delete successfully",
      "ProfileView_22th":"Delete account",
      "ProfileView_23th":"Delete account",
      "ProfileView_24th":"Cancel",
      "ContactView_1st":"Contact Us",
      "ContactView_2nd":"If you have any questions or need assistance, please feel free to contact us via email. We will get back to you as soon as possible.",
      "ContactView_3rd":"Email address",
      "TermsOfServiceView_1st":"Terms of Service",
      "TermsOfServiceView_2nd":"Fake pavilion young talent Zhuzi went to the lamp only to announce the installation of the south, happy bath rice open red elephant tiger before the inch blessing. Buy a nose too bright 'enter the winter sound with the past plant full heavy words home' Ding brother hundred send flat dry today color collection, Guan Mao plant today drink two red ten stand because of class full beg buy help 'brother copy master evening eyes' Bena.",
      "TermsOfServiceView_3rd":"Mouth past teaching or ten you will light early ocean love left present dad import blowing Xiao anti too! Past nose empty south owe far Pakistan gas eye day. Father from the flower often. It sound down eat right how year that is sound because butterfly not who, a sign outside day called buy clothes see? Outside put with phase hair forest.",
      "TermsOfServiceView_4th":"The cup is good. Quickly buy her A with high waves. The evening wind only loves the old sister. The side blows, and the old man blows in. The world is due to the time. The more ancestors, the more they understand. The book is from the north. The lotus is far away from the courtyard. After dinner, the door is very afraid of the gas. The words are used in autumn and summer. Zi Jin Hu Youyou Shao sent Cai Qi and you are beautiful in the new language.",
      "TermsOfServiceView_5th":"Don't two dishes 'Spring Green Fire Open' from the bottom stop back to the ancient more open hat to ask the evening blessing has yellow. Inside the seven strong songs beside the ten, the pavilion road five butterflies thousands of river shells, pine stretch open. The cattle strong autumn cat it rains in the sky tell many butterflies food loaded stone.",
      "TermsOfServiceView_6th":"Pick back to send two gods to dig bitter how to say things. Also green through the flesh of the flower sound Yang Zhuang; to the six questions climb the sound of the inch people plant young complain evening line two mountains? Household borrowed to Guanyang evening lotus Chang brother, father green people step together room also Zhu Shi Hui can endure garden bitter! Left outside the tail? Do shells from the sky, the pavilion spring I. Household ruler painting.",
      "TermsOfServiceView_7th":"vening country urgent level Yingyang hand egg rises Dan eats and flies wind will Zhu! You send temple is jumping drink since now feather urgent tail full too strip owe, that is to show strange that horse temple, food country several color room learn fine year door summer root.",
      "TermsOfServiceView_8th":"The last of my children you now have all the things in the class right to complain. She took the North language girl meat pen shoot through the butterfly bright beg blade help, caught the class rain home land Ni, Ji from the B school, Zhu Ge land tree hide two ancestors.",
      "TermsOfServiceView_9th":"Beiyuan is also like. One yuan to support milk, the ear wind wrong words will be yang milk borrowed to buy the past and the summer air thought.",


      "PrivacyView_title": "Privacy Policy",
      "PrivacyView_paragraph1": "Sample paragraph 1 in English about privacy policy content...",
      "PrivacyView_paragraph2": "Sample paragraph 2 in English about data usage and protection...",
      "PrivacyView_paragraph3": "Sample paragraph 3 explaining how data is handled...",
      "PrivacyView_paragraph4": "Sample paragraph 4 with more details about privacy...",
      "PrivacyView_paragraph5": "Sample paragraph 5 about user rights...",
      "PrivacyView_paragraph6": "Sample paragraph 6 with contact information...",
      "PrivacyView_paragraph7": "Sample paragraph 7 with legal disclaimers...",
      "PrivacyView_paragraph8": "Sample paragraph 8 with updates and changes...",
      "PrivacyView_paragraph9": "Sample paragraph 9 concluding the privacy policy.",





      "UpgarteMemberShiftView_title":"Upgrade AI MusPal",
      "UpgarteMemberShiftView_1st":"Valuable Member",
      "UpgarteMemberShiftView_2nd":"Platinum Member",
      "ValuedMemberView_c1_1st":"Annual Fee Plan",
      "ValuedMemberView_c1_2nd":"HK\$238.5/month",
      "ValuedMemberView_c1_3rd":"HK\$2,862/year",
      "ValuedMemberView_c2_1st":"100 messages per month",
      "ValuedMemberView_c2_2nd":"Maximum length per message: 1,000 characters",
      "ValuedMemberView_c2_3rd":"Up to 4 hours of AI audio rating per month",
      "ValuedMemberView_c2_4th":"300 music analysis reports per month",
      "ValuedMemberView_c3_title":"Auto-renewal instructions",
      "ValuedMemberView_c3_1st":"1. Payment: 'Monthly/quarterly/annual subscriptions' are automatically renewed products. After confirming the purchase, the payment will be deducted from your Apple iTunes account;",
      "ValuedMemberView_c3_2nd":"2. Renewal: 24 hours before your subscription expires, Apple will automatically deduct the fee from your iTunes account. If the renewal is successful, the membership period will be automatically extended.",
      "ValuedMemberView_c3_3rd":"3. If you need to cancel automatic renewal, please manually turn off automatic renewal in the Apple ID account settings at least 24 hours before the subscription expires. No more charges will be made after turning it off.",
      "ValuedMemberView_textField_btn":"Apply",
      "ValuedMemberView_textField_hint":"Enter referral code",
      "ValuedMemberView_roundbtn":"Start your 3-day free trial",
      "ValuedMemberView_bottom":"After subscribing, you will be automatically charged HK\$6528/year. You can manage your subscription by cancelling it in the App store. Terms of Use.",

      "PlatinumMemberView_c1_1st": "Annual Fee Plan",
      "PlatinumMemberView_c1_2nd": "Only HK\$27/hour on average",
      "PlatinumMemberView_c2_1st": "Unlimited messages per month",
      "PlatinumMemberView_c2_2nd": "Up to 2,000 characters per message",
      "PlatinumMemberView_c2_3rd": "Up to 10 hours of AI music  rating per month",
      "PlatinumMemberView_c2_4th": "3,000 music analysis reports per month",
      "PlatinumMemberView_c3_title": "Auto-renewal instructions",
      "PlatinumMemberView_c3_1st": "1. Payment: Subscriptions are automatically renewed. Payment will be deducted from your Apple iTunes account after purchase confirmation.",
      "PlatinumMemberView_c3_2nd": "2. Renewal: 24 hours before your subscription expires, Apple will automatically deduct the renewal fee.",
      "PlatinumMemberView_c3_3rd": "3. To cancel, manually turn off auto-renewal in Apple ID settings at least 24 hours before expiration.",
      "PlatinumMemberView_textField_btn": "Apply",
      "PlatinumMemberView_textField_hint": "Enter referral code",
      "PlatinumMemberView_roundbtn": "Start your 3-day free trial",
      "PlatinumMemberView_bottom": "After subscribing, you will be automatically charged HK\$6528/year. You can cancel anytime in the App Store. Terms of Use apply.",
      "ReferralController_1st":"Referral code has been applied",
      "ReferralController_2nd":"Referral code has been successfully applied",
      "ReferralController_3rd":"Invalid referral code",
      "PaidMemberView_underline_btn":"Manage Subscription",
      "PaidMemberView_date":"Trial period ends on DD/MM/YY",


      "ManageSubscriptionView_title": "Manage Subscription",
      "ManageSubscriptionView_1st": "Your Subscription",
      "ManageSubscriptionView_2nd": "Platinum Member",
      "ManageSubscriptionView_3rd": "Payment Plan",
      "ManageSubscriptionView_4th": "Annual",
      "ManageSubscriptionView_5th": "HK\$2,862",
      "ManageSubscriptionView_6th": "Starting from August 24, your plan will renew at the regular price of HK\$480/month until canceled.",
      "ManageSubscriptionView_btn": "Cancel Subscription",
      "ManageSubscriptionView_alertTitle": "Confirm Cancellation",
      "ManageSubscriptionView_alertContent": "If you confirm and end your subscription now, you can still use the service until September 24, 2024.",
      "ManageSubscriptionView_alertCancel": "Not now",
      "ManageSubscriptionView_alertConfirm": "Confirm",


        "PremiumMemberView_title": "Account",
        "PremiumMemberView_subscribeTitle": "Subscription",
        "PremiumMemberView_planName": "Platinum Member",
        "PremiumMemberView_planDesc": "You're currently on a paid membership plan. Upgrade to get more tokens and send more messages daily.",
        "PremiumMemberView_planIncludes": "Plan Includes",
        "PremiumMemberView_feature1": "Unlimited messages per month",
        "PremiumMemberView_feature2": "Up to 2,000 characters per message",
        "PremiumMemberView_feature3": "Up to 10 hours of AI audio scoring \n per month",
        "PremiumMemberView_feature4": "Up to 3,000 music analysis reports \n per month",
        "PremiumMemberView_manage": "Manage Subscription",
        "PremiumMemberView_upgrade": "Upgrade to Premium",
        "PremiumMemberView_about": "About Us",
        "PremiumMemberView_contact": "Contact Us",
        "PremiumMemberView_terms": "Terms of Service",
        "PremiumMemberView_privacy": "Privacy Policy",
        "PremiumMemberView_logout": "Logout",
        "PremiumMemberView_logoutConfirm": "Are you sure you want to log out?",
        "PremiumMemberView_cancel": "Cancel",
        "PremiumMemberView_delete": "Delete Account",
        "PremiumMemberView_deleteConfirm": "Are you sure you want to permanently delete your account?",
        "PremiumMemberView_deleteDesc": "All data associated with your account will be deleted and cannot be recovered.",

        "AllChatListView_title":"All Conversations",
        "AllChatListView_1st_btn":"AI Conversations",
       "AllChatListView_2nd_btn":"Analysis Conversations",

      "chat_ai_title_1": "How to Understand Music Theory Basics and Phrase Structure 1",
      "chat_ai_title_2": "How to Understand Music Theory Basics and Phrase Structure 2",
      "chat_ai_title_3": "How to Understand Music Theory Basics and Phrase Structure 3",
      "chat_ai_title_4": "How to Understand Music Theory Basics and Phrase Structure 4",
      "chat_subtitle": "Understanding the basics of music theory...",

      "chat_analysis_title_1": "Performance Analysis 1",
      "chat_analysis_title_2": "Performance Analysis 2",
      "chat_analysis_title_3": "Performance Analysis 3",
      "chat_analysis_title_4": "Performance Analysis 4",


      "chat_delete_confirm_title": "Confirm Deletion",
      "chat_delete_confirm_message": "Are you sure you want to delete this conversation? This action cannot be undone.",
      "chat_delete_button": "Delete",
      "chat_cancel_button": "Cancel",
      "chat_snackbar_title": "Tapped",



      "musicChat_title": "New Chat",
      "musicChat_botName": "Violin bot",
      "musicChat_reset": "Reset Complete",
      "musicChat_resetMessage": "Message limit cleared",
      "musicChat_limitWarning": "Today's message limit reached",
      "musicChat_upgrade": "Upgrade",
      "musicChat_upgradeSuccess": "Upgrade Successful",
      "musicChat_premiumWelcome": "You are now a Premium member",
      "musicChat_startHint": "Start a new conversation",
      "musicChat_uploadAttachment": "Upload Attachment",
      "musicChat_camera": "Camera",
      "musicChat_gallery": "Gallery",
      "musicChat_file": "File",
      "musicChat_pdfFile": "PDF File",
      "musicChat_wordFile": "Word Document",
      "musicChat_genericFile": "File" ,

      "violinAnalysis_title": "Analysis Conversation",
      "violinAnalysis_btn": "Start Analysis",

      "violinChat_newConversation": "New Chat",
      "violinChat_botName": "Violin bot",
      "violinChat_welcome": "Welcome. Once you're ready, please upload your audio or video for analysis. Longer clips will take more time.",
      "violinChat_uploadAudioVideo": "Upload Audio/Video",
      "violinChat_uploadAudio": "Upload Audio",
      "violinChat_uploadVideo": "Upload Video",
      "violinChat_uploadScore": "Upload Sheet Music",
      "violinChat_skip": "Skip",
      "violinChat_enterScoreName": "Enter Score Name",
      "violinChat_scorePlaceholder": "Music Score Name",
      "violinChat_confirmScoreTitle": "Confirm Score Name",
      "violinChat_scoreNameIs": "The score name is:",
      "violinChat_scoreNote": "Click back to re-enter the score name.",
      "violinChat_confirmAnalyze": "Confirm and Analyze",
      "violinChat_reenter": "Re-enter",
      "violinChat_analyzing": "Analyzing, please wait...",
      "violinChat_resubmit": "Re-upload",
      "violinChat_viewReport": "View Report",
      "violinChat_audioFile": "Audio File",
      "violinChat_videoFile": "Video File",
      "violinChat_unsupported": "Unsupported message type",
      "violinChat_skipUpload": "User skipped sheet music upload.",
      "violinChat_skipScoreName": "User skipped score name input.",



      "chatReport_title": "Report Analysis",
      "chatReport_totalScore": "Total Score",
      "chatReport_pitch": "Pitch",
      "chatReport_rhythm": "Rhythm",
      "chatReport_dynamics": "Dynamics",
      "chatReport_comment": "Overall Comments",
      "chatReport_rhythmDetails": "Basic music theory... (omitted)",
      "chatReport_dynamicsDetails": "A phrase is typically a complete musical expression...",
      "chatReport_continue": "Continue Chat",
      "chatReport_back": "Back",
      "chatReport_continue_msg": "Function not implemented",

      "chatReport_overallCommentContent": "Very good! You understand the basic concept of phrases.\n\nPitch: A group of phrases forms a section. Understand the relationships and contrasts between sections.\n\nRhythm: A phrase is usually a complete musical expression, similar to a sentence in language.\n\nDynamics: A group of phrases forms a section. Understand the relationships and contrasts between sections.",

      "chatReport_point": "pts",

      "pianoAnalysis_title": "Analysis Chat",
      "pianoAnalysis_button": "Start Analysis",

      "pianoChat_welcomeMsg": "Welcome! When you're ready, upload your audio or video. Longer audio means longer analysis time.",
      "pianoChat_newChat": "New Chat",
      "pianoChat_botName": "Piano bot",
      "pianoChat_audioFile": "Audio File",
      "pianoChat_videoFile": "Video File",
      "pianoChat_unsupported": "Unsupported message type",
      "pianoChat_uploadAudio": "Upload Audio",
      "pianoChat_uploadVideo": "Upload Video",
      "pianoChat_uploadAudioVideo": "Upload Audio/Video",
      "pianoChat_uploadSheetMusic": "Upload Sheet Music",
      "pianoChat_skip": "Skip",
      "pianoChat_provideScoreName": "Provide Score Name",
      "pianoChat_reupload": "Re-upload",
      "pianoChat_confirmScoreName": "Confirm Score Name",
      "pianoChat_scoreNameIs": "Score name is:",
      "pianoChat_clickBackToReenter": "Click back to re-enter score name.",
      "pianoChat_confirmAnalyze": "Confirm and Analyze",
      "pianoChat_userSkippedSheetMusic": "User skipped sheet music upload.",
      "pianoChat_userSkippedScoreName": "User skipped score name input.",
      "pianoChat_uploading": "Uploading...",
      "pianoChat_seeReport": "View Report",


      "bot_response_prefix": "Bot: @msg",
      "user_uploaded_sheet_music": "User uploaded sheet music.",
      "analysis_complete": "Analysis complete! You may check the report.",
      "score_name_label": "Score Name: @name",
      "bot_received_score_name": "Bot received the score name: @name",
      "bot_received_file": "Bot received your @type file."










    },

    'zh_CN' :{
      "registerView_btm":"繼續操作即表示您自動同意 AI Muspal 的使用條款和隱私權政策。",
      'EmailContinueButton_txt':"使用Email繼續",
      'EmailView_1st':"輸入你的電郵地址",
      "EmailView_2nd":'我們會發送6位數驗證碼',
      "EmailView_btn":'下一步',
      "EmailInputField_labelText":'電郵地址',
      "EmailInputField_hintText":'johndoe@gmail.com',
      "OtpView_1st":'輸入6位數驗證碼',
      "OtpView_2nd":'我們已發送驗證碼到Johnxxx@gmail.com',
      "OtpForm_1st":'重新發送驗證碼',
      "OtpForm_2nd":'秒後可重新發送',
      "WelcomeView_1st":'開始聊天吧',
      "WelcomeView_2nd":'你已成功註冊',
      "WelcomeView_btn":'前往體驗',
      "HomeView_1st":'您的',
      "HomeView_2nd":'音樂大師',
      "HomeView_3rd":'學習一切樂理知識',
      "HomeView_4th":'開始對話',
      "HomeView_5th":'AI功能',
      "ProfileView_title":"帳戶",
      "ProfileView_Subscribe":"訂閱",
      "ProfileView_1st":"一般會員",
      "ProfileView_2nd":"你現在正在使用免費會員計劃，升級以獲得更多代幣, 每日可以發送更多訊息",
      "ProfileView_3rd":"計劃包括",
      "ProfileView_4th":"每日 5 條訊息",
      "ProfileView_5th":"每條訊息最多 500 字",
      "ProfileView_6th":"每月最多15分鐘的AI音頻評分",
      "ProfileView_7th":"每月5份音樂分析報告",
      "ProfileView_8th":"升級會員",
      "ProfileView_9th":"關於我們",
      "ProfileView_10th":"聯絡我們",
      "ProfileView_11th":"服務條款",
      "ProfileView_12th":"隱私",
      "ProfileView_13th":"登出",
      "ProfileView_14th":"刪除帳戶",
      "ProfileView_15th":"你確定你要登出嗎",
      "ProfileView_16th":"登出",
      "ProfileView_17th":"取消",
      "ProfileView_18th":"您確定要永久刪除您的帳戶嗎？",
      "ProfileView_19th":"與您帳戶關聯的所有資料都將被刪除且無法恢復。",
      "ProfileView_20th":"帐户删除",
      "ProfileView_21th":"帐号删除成功",
      "ProfileView_22th":"刪除帳戶",
      "ProfileView_23th":"刪除帳戶",
      "ProfileView_24th":"取消",
      "ContactView_1st":"聯絡我們",
      "ContactView_2nd":"如有任何問題或需要協助,歡迎隨時透過電郵與我們聯繫。我們將盡快回覆您。",
      "ContactView_3rd":"電郵地址",
      "TermsOfServiceView_1st":"服務條款",
      "TermsOfServiceView_2nd":"假亭幼才朱字往燈只告裝南，喜澡米開兌象虎前寸福。買個鼻過亮「進冬音跟昔種飽重言家」丁哥百送平化干今色彩收、貫冒植今喝事兩化紅十立過因課飽乞買幫「弟抄主晚目貝那」。",
      "TermsOfServiceView_3rd":"口昔教或十你會光早洋愛左現爸進口吹肖反太！昔鼻空南欠遠巴氣眼日。父自朵常。它聲下吃對怎年即音因蝴不誰，一兆外日叫買衣見？外把以相毛林。",
      "TermsOfServiceView_4th":"杯好告快高波買她甲。夕風話只愛姐綠老。呢助邊吹，進扒吹老。世因候。更祖哪明條北書荷太院遠飯後喝幫怕尼氣門很，話用白瓜根秋夏。子金胡由游少送彩七且你平語新語美呢。",
      "TermsOfServiceView_5th":"勿兩菜「春青火開」從下停回古更開帽問夕乍福己黃。裏七壯歌旁十，亭路五蝴千河貝，松申開。牛壯秋貓它天上雨訴多蝴食裝石。",
      "TermsOfServiceView_6th":"采回送兩神扒苦怎雲事。還青穿肉交花聲陽壯；往六問爬合聲寸人植幼訴夕行兩山？戶借往貫陽晚荷昌兄，爸青人步共室也朱什回忍能園苦！左外丟尾？做貝自，天次亭泉我。戶尺畫。",
      "TermsOfServiceView_7th":"晚國急平英央手蛋升旦吃又飛風會朱！尤送寺正跳喝自今羽急尾飽太條欠，即示怪即馬寺，食國几彩房學細年門夏根。",
      "TermsOfServiceView_8th":"尾我童几您現具西的都斤扒課右訴欠。她帶而北語女肉筆拍貫蝶亮乞刃助，抓課雨家了地尼，吉由乙校，朱歌地樹躲兩祖。",
      "TermsOfServiceView_9th":"貝原也像。一元支奶門耳風錯語會陽奶借色買昔且夏氣想到。",


      "PrivacyView_title": "隱私政策",
      "PrivacyView_paragraph1": "假亭幼才朱字往燈只告裝南，喜澡米開兌象虎前寸福。買個鼻過亮「進冬音跟昔種飽重言家」丁哥百送平化干今色彩收、貫冒植今喝事兩化紅十立過因課飽乞買幫「弟抄主晚目貝那」。",
      "PrivacyView_paragraph2": "口昔教或十你會光早洋愛左現爸進口吹肖反太！昔鼻空南欠遠巴氣眼日。父自朵常。它聲下吃對怎年即音因蝴不誰，一兆外日叫買衣見？外把以相毛林。",
      "PrivacyView_paragraph3": "杯好告快高波買她甲。夕風話只愛姐綠老。呢助邊吹，進扒吹老。世因候。更祖哪明條北書荷太院遠飯後喝幫怕尼氣門很，話用白瓜根秋夏。子金胡由游少送彩七且你平語新語美呢。",
      "PrivacyView_paragraph4": "勿兩菜「春青火開」從下停回古更開帽問夕乍福己黃。裏七壯歌旁十，亭路五蝴千河貝，松申開。牛壯秋貓它天上雨訴多蝴食裝石。",
      "PrivacyView_paragraph5": "采回送兩神扒苦怎雲事。還青穿肉交花聲陽壯；往六問爬合聲寸人植幼訴夕行兩山？戶借往貫陽晚荷昌兄，爸青人步共室也朱什回忍能園苦！左外丟尾？做貝自，天次亭泉我。戶尺畫。",
      "PrivacyView_paragraph6": "晚國急平英央手蛋升旦吃又飛風會朱！尤送寺正跳喝自今羽急尾飽太條欠，即示怪即馬寺，食國几彩房學細年門夏根。",
      "PrivacyView_paragraph7": "尾我童几您現具西的都斤扒課右訴欠。她帶而北語女肉筆拍貫蝶亮乞刃助，抓課雨家了地尼，吉由乙校，朱歌地樹躲兩祖。",
      "PrivacyView_paragraph8": "貝原也像。一元支奶門耳風錯語會陽奶借色買昔且夏氣想到。",
      "PrivacyView_paragraph9": "（最後一段示例文字）",





      "UpgarteMemberShiftView_title":"升級AI MusPal",
      "UpgarteMemberShiftView_1st":"尊貴會員",
      "UpgarteMemberShiftView_2nd":"白金會員",
      "ValuedMemberView_c1_1st":"年費計劃",
      "ValuedMemberView_c1_2nd":"HK\$238.5/月",
      "ValuedMemberView_c1_3rd":"HK\$2,862/年",
      "ValuedMemberView_c2_1st":"每月100條訊息",
      "ValuedMemberView_c2_2nd":"每條訊息最多 1,000 字",
      "ValuedMemberView_c2_3rd":"每月最多4小時的AI音頻評分",
      "ValuedMemberView_c2_4th":"每月300份音樂分析報告",
      "ValuedMemberView_c3_title":"自動續費說明",
      "ValuedMemberView_c3_1st":"1. 付款：“連續包月/季/年”商品為自動續費商品，確認購買後，會從您的蘋果iTunes帳戶扣費；",
      "ValuedMemberView_c3_2nd":"2. 續費：在您訂閱到期前24小時，蘋果會自動從iTunes帳戶扣費，成功後會員有效期自動延長；",
      "ValuedMemberView_c3_3rd":"3. 如需取消自動續費，請在訂閱到期前至少24小時，手動在Apple ID帳戶設置中關閉自動續費，關閉後不再扣費。",
      "ValuedMemberView_textField_btn":"套用",
      "ValuedMemberView_textField_hint":"輸入推薦碼",
      "ValuedMemberView_roundbtn":"開始 3 天免費試用",
      "ValuedMemberView_bottom":"訂閱後，你將被自動扣除HK\$ 6528/年，你可以透過App store取消式管理訂閱。使用條款 。",

      "PlatinumMemberView_c1_1st": "年費計劃",
      "PlatinumMemberView_c1_2nd": "除開只需\$27/1小時",
      "PlatinumMemberView_c2_1st": "每月無條件訊息",
      "PlatinumMemberView_c2_2nd": "每條訊息最多 2,000 字",
      "PlatinumMemberView_c2_3rd": "每月最多 10 小時的 AI 音樂評分",
      "PlatinumMemberView_c2_4th": "每月 3,000 份音樂分析報告",
      "PlatinumMemberView_c3_title": "自動續費說明",
      "PlatinumMemberView_c3_1st": "1. 付款：“連續包月/季/年”商品為自動續費商品，確認購買後，會從您的蘋果iTunes帳戶扣費；",
      "PlatinumMemberView_c3_2nd": "2. 續費：在您訂閱到期前24小時，蘋果會自動從iTunes帳戶扣費，成功後會員有效期自動延長；",
      "PlatinumMemberView_c3_3rd": "3. 如需取消自動續費，請在訂閱到期前至少24小時，手動在Apple ID帳戶設置中關閉自動續費，關閉後不再扣費。",
      "PlatinumMemberView_textField_btn": "套用",
      "PlatinumMemberView_textField_hint": "輸入推薦碼",
      "PlatinumMemberView_roundbtn": "開始 3 天免費試用",
      "PlatinumMemberView_bottom": "訂閱後，你將被自動扣除HK\$ 6528/年，你可以透過App store取消式管理訂閱。使用條款 。",
      "ReferralController_1st":"推薦碼已經套用",
      "ReferralController_2nd":"推薦碼已成功套用",
      "ReferralController_3rd":"推薦碼無效",
      "PaidMemberView_underline_btn":"管理訂閱",
      "PaidMemberView_date":"試用期到DD/MM/YY",



      "ManageSubscriptionView_title": "管理訂閱",
      "ManageSubscriptionView_1st": "你的訂閱",
      "ManageSubscriptionView_2nd": "白金會員",
      "ManageSubscriptionView_3rd": "付費計劃",
      "ManageSubscriptionView_4th": "年費",
      "ManageSubscriptionView_5th": "HK\$2,862",
      "ManageSubscriptionView_6th": "從 8 月 24 日開始，您的計劃將以每月 480 港元的正常價格續訂，直至取消。",
      "ManageSubscriptionView_btn": "取消訂閱",
      "ManageSubscriptionView_alertTitle": "確認取消",
      "ManageSubscriptionView_alertContent": "如果您現在確認並結束訂閱，您仍然可以在 2024 年 9 月 24 日之前使用服務",
      "ManageSubscriptionView_alertCancel": "現在不要",
      "ManageSubscriptionView_alertConfirm": "確認",


      "PremiumMemberView_title": "帳戶",
      "PremiumMemberView_subscribeTitle": "訂閱",
      "PremiumMemberView_planName": "白金會員",
      "PremiumMemberView_planDesc": "你現在正在使用付費會員計劃，升級以獲得更多代幣，每日可以發送更多訊息",
      "PremiumMemberView_planIncludes": "計劃包括",
      "PremiumMemberView_feature1": "每月無限條訊息",
      "PremiumMemberView_feature2": "每條訊息最多 2,000 字",
      "PremiumMemberView_feature3": "每月最多10小時的AI音頻評分",
      "PremiumMemberView_feature4": "每月3,000份音樂分析報告",
      "PremiumMemberView_manage": "管理訂閱",
      "PremiumMemberView_upgrade": "升級成為高級會員",
      "PremiumMemberView_about": "關於我們",
      "PremiumMemberView_contact": "聯絡我們",
      "PremiumMemberView_terms": "服務條款",
      "PremiumMemberView_privacy": "隱私",
      "PremiumMemberView_logout": "登出",
      "PremiumMemberView_logoutConfirm": "你確定你要登出嗎？",
      "PremiumMemberView_cancel": "取消",
      "PremiumMemberView_delete": "刪除帳戶",
      "PremiumMemberView_deleteConfirm": "您確定要永久刪除您的帳戶嗎？",
      "PremiumMemberView_deleteDesc": "與您帳戶關聯的所有資料都將被刪除且無法恢復。",

      "AllChatListView_title":"所有對話",
      "AllChatListView_1st_btn":"AI 對話",
      "AllChatListView_2nd_btn":"分析對話",


      "chat_ai_title_1": "如何理解樂理基礎和樂句結構1",
      "chat_ai_title_2": "如何理解樂理基礎和樂句結構2",
      "chat_ai_title_3": "如何理解樂理基礎和樂句結構3",
      "chat_ai_title_4": "如何理解樂理基礎和樂句結構4",
      "chat_subtitle": "理解音樂理論的基礎...",

      "chat_analysis_title_1": "演奏分析1",
      "chat_analysis_title_2": "演奏分析2",
      "chat_analysis_title_3": "演奏分析3",
      "chat_analysis_title_4": "演奏分析4",



      "chat_delete_confirm_title": "確認刪除",
      "chat_delete_confirm_message": "您確定要刪除此對話嗎？此操作無法撤銷。",
      "chat_delete_button": "刪除",
      "chat_cancel_button": "取消",
      "chat_snackbar_title": "已點擊",


      "musicChat_title": "新的對話",
      "musicChat_botName": "小提琴機器人",
      "musicChat_reset": "重設完成",
      "musicChat_resetMessage": "訊息限制已清除",
      "musicChat_limitWarning": "已達到今天對話上限",
      "musicChat_upgrade": "前往升級",
      "musicChat_upgradeSuccess": "升級成功",
      "musicChat_premiumWelcome": "您現在是 Premium 會員",
      "musicChat_startHint": "開始新對話",
      "musicChat_uploadAttachment": "上傳附件",
      "musicChat_camera": "相機",
      "musicChat_gallery": "相簿",
      "musicChat_file": "檔案",
      "musicChat_pdfFile": "PDF 檔案",
      "musicChat_wordFile": "Word 文件",
      "musicChat_genericFile": "檔案",


      "violinAnalysis_title": "分析對話",
      "violinAnalysis_btn": "開啟分析",


      "violinChat_newConversation": "新的对话",
      "violinChat_botName": "小提琴机器人",
      "violinChat_welcome": "欢迎您，如果您准备好了，可以随时上传你的音频或视频，我会进行下一步分析。音频越长，分析时间会越久。",
      "violinChat_uploadAudioVideo": "上传音频/视频",
      "violinChat_uploadAudio": "上传音频",
      "violinChat_uploadVideo": "上传视频",
      "violinChat_uploadScore": "上传乐谱",
      "violinChat_skip": "略过",
      "violinChat_enterScoreName": "提供乐谱名称",
      "violinChat_scorePlaceholder": "乐谱名称",
      "violinChat_confirmScoreTitle": "确认乐谱名称",
      "violinChat_scoreNameIs": "乐谱名称是：",
      "violinChat_scoreNote": "点选返回可重新输入乐谱名称。",
      "violinChat_confirmAnalyze": "确认并进行分析",
      "violinChat_reenter": "重新输入",
      "violinChat_analyzing": "正在分析中，请稍候…",
      "violinChat_resubmit": "重新上传",
      "violinChat_viewReport": "查看报告",
      "violinChat_audioFile": "音频文件",
      "violinChat_videoFile": "视频文件",
      "violinChat_unsupported": "不支持的消息类型",
      "violinChat_skipUpload": "用户略过了乐谱上传。",
      "violinChat_skipScoreName": "用户略过了输入乐谱名称。",



      "chatReport_title": "報告分析",
      "chatReport_totalScore": "總評分",
      "chatReport_pitch": "音準",
      "chatReport_rhythm": "節拍",
      "chatReport_dynamics": "強弱變化",
      "chatReport_comment": "整體評語",
      "chatReport_rhythmDetails": "學習音樂理論的基礎...（省略）",
      "chatReport_dynamicsDetails": "樂句通常是音樂中的一句完整表達...",
      "chatReport_continue": "繼續對話",
      "chatReport_back": "返回",
      "chatReport_continue_msg": "功能未實作",


      "chatReport_overallCommentContent": "非常不錯！了解基本的樂句概念。\n\n音準：一組樂句構成樂段，理解不同樂段之間的關係和對比。\n\n節拍：了解基本的樂句概念，樂句通常是音樂中的一句完整表達，類似於語言中的一句話。\n\n強弱變化：一組樂句構成樂段，理解不同樂段之間的關係和對比。",

      "chatReport_point": "分",

      "pianoAnalysis_title": "分析對話",
      "pianoAnalysis_button": "開啟分析",

      "pianoChat_welcomeMsg": "歡迎您，如果您準備好了，可以隨時上傳你的音頻或視頻，我會進行下一步分析。, 音頻愈長，分析時間會愈久。",
      "pianoChat_newChat": "新的對話",
      "pianoChat_botName": "Piano bot",
      "pianoChat_audioFile": "音頻文件",
      "pianoChat_videoFile": "視頻文件",
      "pianoChat_unsupported": "不支援的訊息類型",
      "pianoChat_uploadAudio": "上傳音頻",
      "pianoChat_uploadVideo": "上傳視頻",
      "pianoChat_uploadAudioVideo": "上傳音頻/視頻",
      "pianoChat_uploadSheetMusic": "上傳樂譜",
      "pianoChat_skip": "略過",
      "pianoChat_provideScoreName": "供樂譜名稱",
      "pianoChat_reupload": "重新上傳",
      "pianoChat_confirmScoreName": "確認樂譜名稱",
      "pianoChat_scoreNameIs": "樂譜名稱是：",
      "pianoChat_clickBackToReenter": "點選返回可重新輸入樂譜名稱。",
      "pianoChat_confirmAnalyze": "確認並進行分析",
      "pianoChat_userSkippedSheetMusic": "用戶跳過樂譜上傳。",
      "pianoChat_userSkippedScoreName": "用戶跳過樂譜名稱輸入。",
      "pianoChat_uploading": "上傳中...",
      "pianoChat_seeReport": "查看報告",


      "bot_response_prefix": "机器人：@msg",
      "user_uploaded_sheet_music": "使用者上傳了樂譜。",
      "analysis_complete": "分析完成！您可以查看報告。",
      "score_name_label": "樂譜名稱：@name",
      "bot_received_score_name": "机器人已收到樂譜名稱：@name",
      "bot_received_file": "机器人已收到您的@type文件。",










    },

  };
}