
import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations{
  @override
  Map<String,Map<String,String>> get keys =>{

    'en_US' :{
      "registerView_btm":"By continuing you automatically agree to AI Muspal's Terms of Use and Privacy Policy.",
      'EmailContinueButton_txt':"Continue by Email",
      'EmailView_1st':"Enter your email address",
      'EmailView_2nd' :'We will send a 6-digit verification code',
      'EmailView_btn':'Next step',
      'EmailInputField_labelText':"Email address",
      'EmailInputField_hintText':"johndoe@gmail.com",
      "OtpView_1st":'Enter the 6-digit verification code',
      "OtpView_2nd":'We have sent a verification code to Johnxxx@gmail.com',
      "OtpForm_1st":'Resend verification code',
      "OtpForm_2nd":'You can resend after seconds',
      "WelcomeView_1st":"Let's start chatting",
      "WelcomeView_2nd":"You have successfully registered",
      "WelcomeView_btn":"Go to experience",
      "HomeView_1st":"Your",
      "HomeView_2nd":"Music Master",
      "HomeView_3rd":"Learn all about music theory",
      "HomeView_4th":"Start a conversation",
      "HomeView_5th":"AI function",
      "ProfileView_title":"Account",
      "ProfileView_Subscribe":"Subscribe",
      "ProfileView_1st":"general member",
      "ProfileView_2nd":"You are currently using the free membership plan, upgrade to get more tokens and send more messages per day",
      "ProfileView_3rd":"Program includes",
      "ProfileView_4th":"5 messages per day",
      "ProfileView_5th":"Maximum length of each message is 500 characters",
      "ProfileView_6th":"Up to 15 minutes of AI audio rating per month",
      "ProfileView_7th":"5 music analysis reports per month",
      "ProfileView_8th":"Upgrade Membership",
      "ProfileView_9th":"About Us",
      "ProfileView_10th":"Contact Us",
      "ProfileView_11th":"Terms of Service",
      "ProfileView_12th":"Privacy",
      "ProfileView_13th":"Sign out",
      "ProfileView_14th":"Delete Account",
      "ProfileView_15th":"Are you sure you want to log out?",
      "ProfileView_16th":"Sign out",
      "ProfileView_17th":"Cancel",
      "ProfileView_18th":"Are you sure you want to permanently delete your account?",
      "ProfileView_19th":"All data associated with your account will be deleted and cannot be recovered.",
      "ProfileView_20th":"Account delete",
      "ProfileView_21th":"Account delete successfully",
      "ProfileView_22th":"Delete account",
      "ProfileView_23th":"Delete account",
      "ProfileView_24th":"Cancel",
      "ContactView_1st":"Contact Us",
      "ContactView_2nd":"If you have any questions or need assistance, please feel free to contact us via email. We will get back to you as soon as possible.",
      "ContactView_3rd":"Email address",
      "TermsOfServiceView_1st":"Terms of Service",
      "TermsOfServiceView_2nd":"Fake pavilion young talent Zhuzi went to the lamp only to announce the installation of the south, happy bath rice open red elephant tiger before the inch blessing. Buy a nose too bright 'enter the winter sound with the past plant full heavy words home' Ding brother hundred send flat dry today color collection, Guan Mao plant today drink two red ten stand because of class full beg buy help 'brother copy master evening eyes' Bena.",
      "TermsOfServiceView_3rd":"Mouth past teaching or ten you will light early ocean love left present dad import blowing Xiao anti too! Past nose empty south owe far Pakistan gas eye day. Father from the flower often. It sound down eat right how year that is sound because butterfly not who, a sign outside day called buy clothes see? Outside put with phase hair forest.",
      "TermsOfServiceView_4th":"The cup is good. Quickly buy her A with high waves. The evening wind only loves the old sister. The side blows, and the old man blows in. The world is due to the time. The more ancestors, the more they understand. The book is from the north. The lotus is far away from the courtyard. After dinner, the door is very afraid of the gas. The words are used in autumn and summer. Zi Jin Hu Youyou Shao sent Cai Qi and you are beautiful in the new language.",

    },

    'zh_CN' :{
      "registerView_btm":"繼續操作即表示您自動同意 AI Muspal 的使用條款和隱私權政策。",
      'EmailContinueButton_txt':"使用Email繼續",
      'EmailView_1st':"輸入你的電郵地址",
      "EmailView_2nd":'我們會發送6位數驗證碼',
      "EmailView_btn":'下一步',
      "EmailInputField_labelText":'電郵地址',
      "EmailInputField_hintText":'johndoe@gmail.com',
      "OtpView_1st":'輸入6位數驗證碼',
      "OtpView_2nd":'我們已發送驗證碼到Johnxxx@gmail.com',
      "OtpForm_1st":'重新發送驗證碼',
      "OtpForm_2nd":'秒後可重新發送',
      "WelcomeView_1st":'開始聊天吧',
      "WelcomeView_2nd":'你已成功註冊',
      "WelcomeView_btn":'前往體驗',
      "HomeView_1st":'您的',
      "HomeView_2nd":'音樂大師',
      "HomeView_3rd":'學習一切樂理知識',
      "HomeView_4th":'開始對話',
      "HomeView_5th":'AI功能',
      "ProfileView_title":"帳戶",
      "ProfileView_Subscribe":"訂閱",
      "ProfileView_1st":"一般會員",
      "ProfileView_2nd":"你現在正在使用免費會員計劃，升級以獲得更多代幣, 每日可以發送更多訊息",
      "ProfileView_3rd":"計劃包括",
      "ProfileView_4th":"每日 5 條訊息",
      "ProfileView_5th":"每條訊息最多 500 字",
      "ProfileView_6th":"每月最多15分鐘的AI音頻評分",
      "ProfileView_7th":"每月5份音樂分析報告",
      "ProfileView_8th":"升級會員",
      "ProfileView_9th":"關於我們",
      "ProfileView_10th":"聯絡我們",
      "ProfileView_11th":"服務條款",
      "ProfileView_12th":"隱私",
      "ProfileView_13th":"登出",
      "ProfileView_14th":"刪除帳戶",
      "ProfileView_15th":"你確定你要登出嗎",
      "ProfileView_16th":"登出",
      "ProfileView_17th":"取消",
      "ProfileView_18th":"您確定要永久刪除您的帳戶嗎？",
      "ProfileView_19th":"與您帳戶關聯的所有資料都將被刪除且無法恢復。",
      "ProfileView_20th":"帐户删除",
      "ProfileView_21th":"帐号删除成功",
      "ProfileView_22th":"刪除帳戶",
      "ProfileView_23th":"刪除帳戶",
      "ProfileView_24th":"取消",
      "ContactView_1st":"聯絡我們",
      "ContactView_2nd":"如有任何問題或需要協助,歡迎隨時透過電郵與我們聯繫。我們將盡快回覆您。",
      "ContactView_3rd":"電郵地址",
      "TermsOfServiceView_1st":"服務條款",
      "TermsOfServiceView_2nd":"假亭幼才朱字往燈只告裝南，喜澡米開兌象虎前寸福。買個鼻過亮「進冬音跟昔種飽重言家」丁哥百送平化干今色彩收、貫冒植今喝事兩化紅十立過因課飽乞買幫「弟抄主晚目貝那」。",
      "TermsOfServiceView_3rd":"口昔教或十你會光早洋愛左現爸進口吹肖反太！昔鼻空南欠遠巴氣眼日。父自朵常。它聲下吃對怎年即音因蝴不誰，一兆外日叫買衣見？外把以相毛林。",
      "TermsOfServiceView_4th":"杯好告快高波買她甲。夕風話只愛姐綠老。呢助邊吹，進扒吹老。世因候。更祖哪明條北書荷太院遠飯後喝幫怕尼氣門很，話用白瓜根秋夏。子金胡由游少送彩七且你平語新語美呢。",

    },

  };
}